# Generated by Django 5.0.2 on 2024-02-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
