# Generated by Django 5.0.2 on 2024-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0008_cometario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cometario',
            name='autor',
            field=models.CharField(default='anónimo', max_length=255),
        ),
    ]
