# Generated by Django 5.0.2 on 2024-02-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0011_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
